### ISSUE TITLE
リンク周りの細かい修正

### ISSUE THREAD

**Issue by jumtech** [zuckeyM-17/shiganai-radio-v2#41]
## TODO
- [x] フッターのリンク周りを全体的にclickableっぽくする
    - [x] `#しがないラジオ`
    - [x] RSSフィード
    - [x] サイトマップ
- [x] `target="_blank"`
    - [x] フッター
        - [x] `#しがないラジオ`
        - [x] Copyrightの`zuckey`と`gami`
    - [x] ホスト
        - [x] 諸々
- [x] リンク時のスクロール
    - [x] フッター
        - [x] to ホーム
        - [x] to パーソナリティ
        - [x] to ゲスト
    - [x] ゲスト一覧
        - [x] to ゲスト詳細
    - [x] ゲスト詳細
        - [x] to ep詳細

**Comment by hkdnet** [comment]
it seems to be done
